<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HaberKategorileriSeeder extends Seeder
{
    public function run(): void
    {
        // Soft-delete ile silinmiş eski kayıtları kalıcı olarak temizle
        \App\Models\HaberKategorisi::onlyTrashed()->forceDelete();

        $kategoriler = [
            [
                'ad'               => 'Eğitim',
                'slug'             => 'egitim',
                'renk'             => '#2563EB',
                'seo_baslik'       => 'Kestanepazarı Eğitim Faaliyetleri ve Kur\'an Kurslarımız',
                'meta_description' => 'Öğrencilerimize sunduğumuz ücretsiz tam pansiyon yatılı Kur\'an, hafızlık, İmam Hatip ve İlahiyat eğitim destek programlarımız.',
                'aciklama'         => '<h2>Eğitim ve Gelişim Programlarımız</h2><p>Kestanepazarı olarak asırlık tecrübemizle, Kur\'an-ı Kerim\'i anlayan ve yaşayan vatansever nesiller yetiştiriyoruz. Merkez, Hatay, Aliağa ve 7-10 yaş şubelerimizde öğrencilerimize ücretsiz tam pansiyon yatılı eğitim imkânı sunuyor; onları akademik ve manevi yönden geleceğe hazırlıyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-book-open',
                'sira'             => 1,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Etkinlik',
                'slug'             => 'etkinlik',
                'renk'             => '#F43F5E',
                'seo_baslik'       => 'Etkinlikler, Seminerler ve Genç Yıldızlar Programları',
                'meta_description' => 'Kestanepazarı bünyesinde düzenlenen seminerler, konferanslar, Genç Yıldızlar Yaz programları ve özel etkinliklerimiz.',
                'aciklama'         => '<h2>Sosyal ve Kültürel Etkinliklerimiz</h2><p>Öğrencilerimizin manevi eğitimlerinin yanı sıra sosyal yönlerini de güçlendirmek amacıyla çeşitli etkinlikler düzenliyoruz. Yıl içi programlarımız ve yaz aylarındaki Genç Yıldızlar Yaz Kur\'an Kursu etkinliklerimizle gençlerimizin gelişimini çok yönlü destekliyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-calendar-days',
                'sira'             => 2,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Başarı',
                'slug'             => 'basari',
                'renk'             => '#EAB308',
                'seo_baslik'       => 'Öğrenci ve Hafızlık Başarılarımız | Kestanepazarı',
                'meta_description' => 'Kur\'an kursu ve okul öğrencilerimizin elde ettiği hafızlık dereceleri, akademik başarılar ve gurur tablolarımız.',
                'aciklama'         => '<h2>Başarılarımız ve Gurur Tablomuz</h2><p>İlim ve bilim yolunda yetiştirdiğimiz talebelerimizin akademik sınavlarda, Kur\'an-ı Kerim\'i güzel okuma ve hafızlık yarışmalarında elde ettiği başarıları buradan paylaşıyoruz. Her bir başarı, Kestanepazarı eğitim ekolünün ve ihlaslı çalışmaların bir meyvesidir.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-award',
                'sira'             => 3,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Röportaj',
                'slug'             => 'roportaj',
                'renk'             => '#8B5CF6',
                'seo_baslik'       => 'Kestanepazarı Özel Röportajları ve Söyleşiler',
                'meta_description' => 'Kıymetli hocalarımız, binlerce mezunumuz ve eğitim kadromuzla gerçekleştirdiğimiz ilham verici özel röportajlar.',
                'aciklama'         => '<h2>Özel Röportajlar ve Söyleşiler</h2><p>Tarihte bir ekol olan kurumumuza değer katan değerli hocalarımızla, devletine ve milletine hizmet eden kıymetli mezunlarımızla gerçekleştirdiğimiz ufuk açıcı söyleşileri bu bölümde derliyoruz. Geçmişten geleceğe tecrübe aktarımını çok önemsiyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-microphone-lines',
                'sira'             => 4,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Spor',
                'slug'             => 'spor',
                'renk'             => '#EF4444',
                'seo_baslik'       => 'Talebelerimiz İçin Sportif Faaliyetler ve Turnuvalar',
                'meta_description' => 'Gençlerimizin fiziksel gelişimini destekleyen spor müsabakaları, kurum içi turnuvalar ve sağlıklı yaşam etkinliklerimiz.',
                'aciklama'         => '<h2>Sportif Faaliyetler ve Sağlıklı Yaşam</h2><p>Hafızlık ve akademik eğitimlerini sürdüren öğrencilerimizin zihinsel gelişimi kadar fiziksel gelişimlerini de önemsiyoruz. Kurumlarımız bünyesinde düzenlenen spor turnuvaları ve fiziksel etkinlik haberlerini buradan takip edebilirsiniz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-volleyball',
                'sira'             => 5,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Gezi',
                'slug'             => 'gezi',
                'renk'             => '#84CC16',
                'seo_baslik'       => 'Öğrenci Kültür Gezileri ve Doğa Kampları',
                'meta_description' => 'Öğrencilerimiz için düzenlediğimiz tarih ve kültür gezileri, doğa kampları ve ufuk açıcı seyahat programları.',
                'aciklama'         => '<h2>Kültür Gezileri ve Doğa Kampları</h2><p>Talebelerimizin tarihi ve kültürel mirasımızı yerinde görmeleri, doğayla iç içe vakit geçirmeleri amacıyla periyodik olarak kültür gezileri organize ediyoruz. Öğrencilerimizin moral ve motivasyonunu artıran bu gezilerin detayları sayfamızdadır.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-bus',
                'sira'             => 6,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Kur\'an Ziyafeti',
                'slug'             => 'kuran-ziyafeti',
                'renk'             => '#059669',
                'seo_baslik'       => 'Kur\'an-ı Kerim Ziyafeti Programları ve Tilavetler',
                'meta_description' => 'Görevli hocalarımız ve hafız talebelerimiz tarafından halkımıza yönelik düzenlenen Kur\'an-ı Kerim ziyafeti programlarımız.',
                'aciklama'         => '<h2>Kur\'an-ı Kerim Ziyafeti Programları</h2><p>Kurumlarımızda görevli hocalarımız ve hafız talebelerimiz tarafından, Kur\'an\'ın öğretilmesi ve anlaşılması doğrultusunda halkımıza yönelik düzenlenen Kur\'an Ziyafeti programlarını buradan takip edebilirsiniz. Gönülleri nurlandıran tilavetlerle manevi iklimi paylaşıyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-quran',
                'sira'             => 7,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Ziyaret',
                'slug'             => 'ziyaret',
                'renk'             => '#64748B',
                'seo_baslik'       => 'Kurumsal Ziyaretler ve Protokol Temasları',
                'meta_description' => 'Yapılan resmi makam ziyaretleri, protokol görüşmeleri ve sivil toplum kuruluşu temasları.',
                'aciklama'         => '<h2>Kurumsal Ziyaretler ve Temaslar</h2><p>Resmi makam ziyaretleri, protokol görüşmeleri ve eğitim vizyonumuzu paylaşan sivil toplum kuruluşlarıyla gerçekleştirdiğimiz kurumsal temaslar bu bölümde yer almaktadır. Birlik ve beraberliğimizi pekiştiren buluşmaları güncel olarak paylaşıyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-handshake',
                'sira'             => 8,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Mezunlarımız',
                'slug'             => 'mezunlarimiz',
                'renk'             => '#D97706',
                'seo_baslik'       => 'Kestanepazarı Mezunları ve Ahde Vefa Buluşmaları',
                'meta_description' => '10 binin üzerinde vatan evladı ve binlerce hafız yetiştiren kurumumuzun mezun haberleri ve ahde vefa buluşmaları.',
                'aciklama'         => '<h2>Mezunlarımız ve Ahde Vefa</h2><p>Kestanepazarı eğitim ocağından feyiz alarak yurdun ve dünyanın dört bir yanına dağılan, devletine ve milletine hizmet eden binlerce hafız ve mezunumuzun haberlerini, başarılarını ve geleneksel ahde vefa buluşmalarımızı bu çatı altında topluyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-user-graduate',
                'sira'             => 9,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Kurban',
                'slug'             => 'kurban',
                'renk'             => '#9F1239',
                'seo_baslik'       => 'Kurban Organizasyonu, Vekalet ve Bağış Faaliyetleri',
                'meta_description' => 'Emanetlerinizi büyük bir hassasiyetle talebelerimize ve ihtiyaç sahiplerine ulaştırdığımız Kurban organizasyonlarımız.',
                'aciklama'         => '<h2>Kurban Organizasyonları ve Bağış Faaliyetleri</h2><p>İyiliğin ve paylaşmanın sembolü olan Kurban ibadetini layıkıyla yerine getirmek için düzenlediğimiz bağış ve kesim organizasyonlarımızın detaylarını buradan takip edebilirsiniz. Hayırsever halkımızın emanetlerini tam pansiyon okuyan talebelerimize ve ihtiyaç sahiplerine ulaştırıyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-hand-holding-heart',
                'sira'             => 10,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Ramazan',
                'slug'             => 'ramazan',
                'renk'             => '#1E3A8A',
                'seo_baslik'       => 'Ramazan İklimi: Zekat, Fitre ve Kur\'an Programları',
                'meta_description' => 'Ramazan aylarında halkımıza yönelik gerçekleştirdiğimiz organizasyonlar.',
                'aciklama'         => '<h2>Ramazan Ayı Faaliyetleri ve Yardımlaşma</h2><p>Rahmet ayı Ramazan-ı Şerif\'te hocalarımız ve hafızlarımızla gerçekleştirdiğimiz mukabele ve Kur\'an programlarının yanı sıra; iftar, zekat ve fitre organizasyonlarımız bu sayfada yer almaktadır. Ramazan\'ın bereketini Kestanepazarı ailesi olarak hep birlikte paylaşıyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-moon',
                'sira'             => 11,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Hafızlık İcazet Merasimi',
                'slug'             => 'hafizlik-icazet-merasimi',
                'renk'             => '#4338CA',
                'seo_baslik'       => 'Hafızlık İcazet Merasimleri ve Taç Giyme Törenleri',
                'meta_description' => 'Kur\'an-ı Kerim\'i en güzel biçimde okuyabilen hafızlar yetiştirme gayemizin tacı olan geleneksel icazet merasimlerimiz.',
                'aciklama'         => '<h2>Hafızlık İcazet Merasimleri</h2><p>Kestanepazarı\'nın asıl gayesi olan, Kur\'an-ı Kerim\'i hıfzeden yavrularımızın taç giydiği <strong>Hafızlık İcazet Merasimleri</strong> ile ilgili tüm coşkuyu ve haberleri bu kategoride bulabilirsiniz. Kur\'an muhafızlarının yetişmesinde emeği geçen hayırseverlerimize şükranlarımızı sunuyoruz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-crown',
                'sira'             => 12,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Kurumsal',
                'slug'             => 'kurumsal',
                'renk'             => '#0F172A',
                'seo_baslik'       => 'Kurumsal Haberler ve Dernek Yönetim Duyuruları',
                'meta_description' => '1948 yılında kurulan Kestanepazarı Öğrenci Yetiştirme Derneği\'nin yönetim kurulu kararları ve resmi bilgilendirmeleri.',
                'aciklama'         => '<h2>Kurumsal Bilgilendirmeler ve Yönetim Haberleri</h2><p>1668 yılına uzanan kökleri ve 1948 yılındaki dernekleşme süreciyle asırlık bir çınar olan Kestanepazarı Öğrenci Yetiştirme Derneği\'nin işleyişi, yönetim kurulu faaliyetleri ve vizyonumuz doğrultusunda atılan adımlara ait kurumsal haberlere buradan ulaşabilirsiniz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-building',
                'sira'             => 13,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Haber',
                'slug'             => 'haber',
                'renk'             => '#0EA5E9',
                'seo_baslik'       => 'Kestanepazarı Güncel Haberler ve Kurum İçi Gelişmeler',
                'meta_description' => 'Aliağa, Hatay, Merkez şubelerimizdeki en güncel gelişmeler, eğitim dünyasından haberler ve basındaki yansımalarımız.',
                'aciklama'         => '<h2>Güncel Haberler ve Gelişmeler</h2><p>Eğitim kadromuzdan, Kur\'an kursu şubelerimizden (Merkez, Hatay, Aliağa) ve genel işleyişimizden yansıyan en güncel haberleri bu bölümde derliyoruz. Faaliyet alanlarımızla ilgili sıcak gelişmelerden anında haberdar olmak için bu sayfayı takip edebilirsiniz.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-newspaper',
                'sira'             => 14,
                'aktif'            => true,
            ],
            [
                'ad'               => 'Duyuru',
                'slug'             => 'duyuru',
                'renk'             => '#F97316',
                'seo_baslik'       => 'Önemli Duyurular, Kayıt Süreçleri ve İlanlar',
                'meta_description' => 'Öğrenci kabul dönemleri, ücretsiz yatılılık sınavları, yaz okulu kayıt süreçleri ve yayınlanan diğer önemli duyurular.',
                'aciklama'         => '<h2>Önemli Duyurular ve İlanlar</h2><p>Yeni eğitim öğretim dönemi kayıtları, ücretsiz yatılılık/bursluluk sınav tarihleri, Genç Yıldızlar Yaz Kur\'an Kursu başvuru süreçleri ve etkinlik takvimlerimize dair resmi duyurular bu kategoride yayınlanmaktadır.</p>',
                'gorsel'           => null,
                'ikon'             => 'fa-solid fa-bullhorn',
                'sira'             => 15,
                'aktif'            => true,
            ],
        ];

        foreach ($kategoriler as $sira => $kategori) {
            \App\Models\HaberKategorisi::withTrashed()
                ->updateOrCreate(
                    ['slug' => $kategori['slug']],
                    array_merge($kategori, ['deleted_at' => null])
                );
        }
    }
}
